version: '3.8'

services:
  backend:
    build: ./backend
    container_name: youtube-downloader-api
    ports:
      - "3001:3001"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - NODE_ENV=production
    networks:
      - youtube-downloader-network

  frontend:
    build: ./frontend
    container_name: youtube-downloader-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - youtube-downloader-network

networks:
  youtube-downloader-network:
    driver: bridge

volumes:
  downloads: 